Repository nmklotas/GitLabApiClient, pull requests merged in 2020-09, with the labels that each got.

#167 Add user to the group now actually works
  docker/init.rb
  src/GitLabApiClient/GroupsClient.cs
  src/GitLabApiClient/Models/Groups/Requests/AddGroupMemberRequest.cs
  test/GitLabApiClient.Test/GroupsClientTest.cs
  test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs
Labels: bug

#158 Add value for CannotBeMerged in Status
  src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequestState.cs
Labels: chore

#168 Add option to force random password option when creating new user
  src/GitLabApiClient/Models/Users/Requests/CreateUserRequest.cs
Labels: enhancement

#164 Add missing enum member `checking` to the MergeStatus.cs
  src/GitLabApiClient/Models/MergeRequests/Responses/MergeStatus.cs
Labels: enhancement

#92 Project import export
  src/GitLabApiClient/GitLabClient.cs
  src/GitLabApiClient/IProjectsClient.cs
  src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
  src/GitLabApiClient/Internal/Http/GitlabApiRequestor.cs
  src/GitLabApiClient/Models/Projects/Requests/ImportProjectRequest.cs
  src/GitLabApiClient/Models/Projects/Responses/ExportLinks.cs
  src/GitLabApiClient/Models/Projects/Responses/ExportStatus.cs
  src/GitLabApiClient/Models/Projects/Responses/ExportStatusEnum.cs
  src/GitLabApiClient/Models/Projects/Responses/ImportStatus.cs
  src/GitLabApiClient/Models/Projects/Responses/ImportStatusEnum.cs
  src/GitLabApiClient/ProjectsClient.cs
  test/GitLabApiClient.Test/ProjectsClientTest.cs
Labels: enhancement

#163 Processes Merged By Object from Merge Request Response
  src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequest.cs
  test/GitLabApiClient.Test/MergeRequestClientTest.cs
Labels: enhancement

#161 Update runners command
  docker/init.rb
  src/GitLabApiClient/GroupsClient.cs
  src/GitLabApiClient/IGroupsClient.cs
  src/GitLabApiClient/IRunnersClient.cs
  src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
  src/GitLabApiClient/Internal/Http/GitlabApiRequestor.cs
  src/GitLabApiClient/Models/Runners/Requests/CreateRunnerRequest.cs
  src/GitLabApiClient/Models/Runners/Requests/UpdateRunnerRequest.cs
  src/GitLabApiClient/Models/Runners/Responses/RunnerDetails.cs
  src/GitLabApiClient/Models/Runners/Responses/RunnerProject.cs
  src/GitLabApiClient/Models/Runners/Responses/RunnerToken.cs
  src/GitLabApiClient/RunnersClient.cs
  test/GitLabApiClient.Test/GroupsClientTest.cs
  test/GitLabApiClient.Test/ProjectsClientTest.cs
  test/GitLabApiClient.Test/RunnersClientTest.cs
  test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs
  test/GitLabApiClient.Test/Utilities/GitLabContainerFixture.cs
Labels: enhancement

#173 Rename ressources to resources
  test/GitLabApiClient.Test/GitLabApiClient.Test.csproj
  test/GitLabApiClient.Test/Resources/gitlabtest.png
Labels: bug
