Repository nmklotas/GitLabApiClient, pull requests merged in 2020-01, with the labels that each got.

#77 add files and trees client
  docker/init.rb
  src/GitLabApiClient/FilesClient.cs
  src/GitLabApiClient/GitLabClient.cs
  src/GitLabApiClient/Internal/Queries/TreeQueryBuilder.cs
  src/GitLabApiClient/Models/Files/Responses/File.cs
  src/GitLabApiClient/Models/Trees/Requests/TreeQueryOptions.cs
  src/GitLabApiClient/Models/Trees/Responses/Tree.cs
  src/GitLabApiClient/TreesClient.cs
  test/GitLabApiClient.Test/FilesClientTest.cs
  test/GitLabApiClient.Test/GitLabClientTest.cs
  test/GitLabApiClient.Test/TreesClientTest.cs
Labels: enhancement

#106 bump git version
  GitVersion.yml
  appveyor.yml
  src/GitLabApiClient/GitLabApiClient.csproj
Labels: dependencies

#108 gitversion: use continuous deployment mode
  GitVersion.yml
  src/GitLabApiClient/GitLabApiClient.csproj
  test.ps1
Labels: skip-changelog

#99 add group labels and issues methods
  src/GitLabApiClient/GitLabClient.cs
  src/GitLabApiClient/GroupsClient.cs
  src/GitLabApiClient/Internal/Queries/GroupLabelsQueryBuilder.cs
  src/GitLabApiClient/Internal/Queries/IssuesQueryBuilder.cs
  src/GitLabApiClient/Internal/Queries/ProjectIssuesQueryBuilder.cs
  src/GitLabApiClient/IssuesClient.cs
  src/GitLabApiClient/Models/Groups/Requests/CreateGroupLabelRequest.cs
  src/GitLabApiClient/Models/Groups/Requests/GroupLabelsQueryOptions.cs
  src/GitLabApiClient/Models/Groups/Requests/UpdateGroupLabelRequest.cs
  src/GitLabApiClient/Models/Groups/Responses/GroupLabel.cs
  src/GitLabApiClient/Models/Issues/Requests/IssuesQueryOptions.cs
  src/GitLabApiClient/Models/Issues/Requests/ProjectIssuesQueryOptions.cs
  test/GitLabApiClient.Test/GroupsClientTest.cs
  test/GitLabApiClient.Test/Internal/Queries/GroupLabelsQueryBuilderTest.cs
  test/GitLabApiClient.Test/Internal/Queries/IssuesQueryBuilderTest.cs
  test/GitLabApiClient.Test/Internal/Queries/ProjectIssuesQueryBuilderTest.cs
  test/GitLabApiClient.Test/IssuesClientTest.cs
Labels: enhancement

#114 use checkout@v2 and fetch prune unshallow
  .github/workflows/ci.yml
Labels: skip-changelog
